# -*- coding: utf-8 -*-
"""PSDL_mini.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xVFLsdlh3jPJveE9wQKoCLr8acjkpk-2

# **SWAYAM**
## Be your own doctor
"""

pip install colorama

pip install fontstyle

def patient():
  import pandas as pd
  import math
  import colorama
  from colorama import Fore

#read data from a file with path ('filename.csv')

#df= pd.read_csv('Book7.csv') # normal data

  df= pd.read_csv('excess2.csv')
  df1=pd.read_csv('deficiency1.csv')
  df2=pd.read_csv('Abovelevel.csv')

  print("\n\t Patient data ")
  print("\n")

  print(df)
  print("\n\n")

import pandas as pd
import math
import colorama
from colorama import Fore

def prediction():
 df= pd.read_csv('excess2.csv')
 df1=pd.read_csv('deficiency1.csv')
 df2=pd.read_csv('Abovelevel.csv')
 inp = df['obsereved'].tolist()
 inp1 = df['low'].tolist()
 inp2 = df['high'].tolist() #list of high range
 inp3 = df['Parameter'].tolist() #list of high range
 inp4 = df1['disorder'].tolist() #list of high range
 inp5 = df1['remedies'].tolist() #list of high range
 inp6 = df2['disorder'].tolist() #list of high range
 inp7 = df2['remedies'].tolist()

 flag=0
 flag1=0
 l1=[]
 l2=[]
 for i in range(len(inp)):
   if(inp[i]<inp1[i]):
     l1.append(i)
     flag=1
   if(inp[i]>inp2[i]):
     l2.append(i)
     flag1=1
 if(flag1==0 and flag==0):
   print(Fore.GREEN +"\n\t--------------------- :) :) :) YOU ARE COMPLETELY FIT (: (: (: -----------------")
 else:
  for i in l1:
    print(Fore.BLACK+"\n\t Deficiency in :   ",Fore.RED +inp3[i])
    print(Fore.BLACK+"\n\t Disorder predicted : ",Fore.RED +inp4[i])
    print(Fore.BLACK+"\n\t Remedies : ",Fore.BLUE+inp5[i])
    print(Fore.BLACK+"\n\t-----------------------------------------------------------------------------")
  for i in l2:
    print(Fore.BLACK+"\n\t Above level :  ", Fore.RED + inp3[i])
    print(Fore.BLACK+"\n\t Disorder predicted : ",Fore.RED + inp6[i])
    print(Fore.BLACK+"\n\t Remedies : ",Fore.BLUE +inp7[i])
    print(Fore.BLACK+"\n\t-----------------------------------------------------------------------------")

#height,weight BMI
# height,weight BMI

def bmi_calculate(height,weight,age):
 flag=0
 flag1=0

 if age<20:

    bmi = (weight / (height * height)) #still left for child
    print(bmi)

 else:
    bmi = (weight / (height * height))

    if bmi < 18.5:
        print("\n  BMI   \t\t\t\t\t  {:.2f}".format(bmi),"\t\t Status : UnderWeight ")
        flag=1
        return flag

    elif 18.5 < bmi < 24.9:
        print("\n  BMI   \t\t\t\t  {:.2f}".format(bmi), "\t\t Status : Normal " )

    elif 25 < bmi < 29.9:
        print("\n  BMI  \t\t\t\t\t  {:.2f}".format(bmi), "\t\t Status : Overweight " )
        flag=2
        return flag

    elif bmi > 30.0:
        print("\n  BMI   \t\t\t\t\t  {:.2f}".format(bmi), "\t\t Status : Obese " )

def display(name,gender,age,date,height,weight):
 df= pd.read_csv('excess2.csv')
 df1=pd.read_csv('deficiency1.csv')
 df2=pd.read_csv('Abovelevel.csv')
 inp = df['obsereved'].tolist()
 inp1 = df['low'].tolist()
 inp2 = df['high'].tolist() #list of high range
 inp3 = df['Parameter'].tolist() #list of high range
 inpu=[ '%.2f ' % elem for elem in inp]
 inpu1 = [ '%5.f ' % elem for elem in inp1]
 inpu2 = [ '%5.f ' % elem for elem in inp2]
 l1=['blood sugur', 'BUN        ', 'calcium', 'cholestrol', 'iron       ', 'magnesium', 'phosphate', 'platelet', 'potassium', 'sodium', 'uric acid', 'WBC        ']
 inp4 = df1['disorder'].tolist() #list of high range
 inp5 = df1['remedies'].tolist() #list of high range
 inp6 = df2['disorder'].tolist() #list of high range
 inp7 = df2['remedies'].tolist()
 print("\n\n")
 print("-"*100)
 print("**************************************** ANALYSIS REPORT ******************************************* ")
 print("-"*100)
 print("\n\tName : ",name,"\t\t\t\t\t\t Date  : ",date)
 print("\n\tAge : ",age,"\t\t\t\t\t\t Height  : ",height,"m")
 print("\n\tGender : ",gender,"\t\t\t\t\t\t Weight  : ",weight,"kg")
 print("_"*100)
 print("\n")
 print("-"*100)
 print("\t Parameter ","\t\t\t Tested value ","\t\t\t Range")
 print("-"*100)
 for i in range(len(inp3)):
   print("\n ",l1[i],"\t\t\t\t ",inpu[i],"\t\t ",inpu1[i],"  -  ",inpu2[i])

# Join all code
import fontstyle
choice=0
while(choice!=7):
 print('\033[1m'+"\n___________________________________________________\t    SVAYAM  \t_________________________________________________")
 text = fontstyle.apply(' Be your own doctor ', 'Italic/red')
 print('\033[0m'+"\n\t\t\t\t\t\t    "+text)
 print("\n\t--------------------HOME--------------------")
 print("\n\t 1. Patient Details ")
 print("\n\t 2. Patient report  ")
 print("\n\t 3. Report Analysis ")
 print("\n\t 4. Defiency Chart display ")
 print("\n\t 5. Excess Level Chart display ")
 print("\n\t 6. BMI Measurement ")
 print("\n\t 7. Exit ")
 choice=(int)(input("\n\t Enter your choice :  "))

 if(choice==1):
   print("\n\t ---------------------------------::: Patient Personal Details ::::-------------------------------")
   name=input("\n\t\t Enter Name : ")
   age=(float)(input("\n\t Enter age : "))
   gender=input("\n\t Enter gender : ")
   date=input("\n\t Enter date : ")
   height=(float)(input("\n\t Enter height : "))
   weight=(float)(input("\n\t Enter weight : "))
   print("\n\t -------------------------------------------------------------------------------------------------")
 elif(choice==2):
   patient()
   print("\n----------------------------------------------------------------------------------------------------")
 elif(choice==3):
   display(name,gender,age,date,height,weight)
   x=bmi_calculate(height,weight,age)
   print("\n")
   print("_"*100)
   print("-"*100)
   print("**************************************** SUGGESTIONS  ******************************************* ")
   print("-"*100)
   prediction()
   #print(x)
   if(x==1):
         print("\n\t ******************* Remedies to gain weight **************************")
         print("\n\t 1.Eat more frequently. When you're underweight, you may feel full faster\n\t 2.Choose nutrient-rich "
                "foods\n\t 3.Try smoothies and shakes\n\t 4.Watch when you drink\n\t 5.Exercise")
   if(x==2):
          print("\n\t **************************** Remedies to lose weight ********************")
          print("\n\t 1.Drinking lemon water with honey\n\t 2.Powder of fenugreek seeds, carom seeds and black cumin "
                "seeds:\n\t 3.Stop consuming artificial sugars:\n\t 4.Eat in a small plate")



def wbc(hemoglobin):

 #hemoglobin = float(input("\n\t Enter hemoglobin in g/dl :"))  # in grams per deciliter (g/dl)
 flag = 0
 flag1 = 0
 rem1=0
 rem2=0

 if gender == "m":
    # age = int(input("Enter your Age : "))
    if 12 < age <= 18:
        if hemoglobin < 13.6:
            flag = 1
        if hemoglobin > 17.7:
            flag1 = 1
        elif 13.6 < hemoglobin <= 17.7:
            print("\n\t Hemoglobin: Normal ")
    if 18 < age <= 50:
        if hemoglobin < 13.6:
            flag = 1
        if hemoglobin > 17.7:
            flag1 = 1
        elif 13.6 < hemoglobin <= 17.7:
            print("\n\t Hemoglobin: Normal ")
    if age > 50:
        if hemoglobin < 12.4:
            flag = 1
        if hemoglobin > 14.9:
            flag1 = 1

        elif 12.4 < hemoglobin <= 14.9:
            print("\n\t Hemoglobin: Normal ")
 if gender == "w":
    #age = int(input("Enter your Age : "))
    if 12 < age <= 18:
        if hemoglobin < 12.0:
            flag = 1
        if hemoglobin > 16.0:
            flag1 = 1
        elif 12.0 < hemoglobin <= 16.0:
            print("\n\t Hemoglobin : Normal ")
    if 18 < age <= 50:
        if hemoglobin < 12.1:
            flag = 1
        if hemoglobin > 15.1:
            flag1 = 1
        elif 12.1 < hemoglobin <= 15.1:
            print("\n\t Hemoglobin : Normal ")
    if age > 50:
        if hemoglobin < 11.7:
            flag = 1
        if hemoglobin > 13.8:
            flag1 = 1
        elif 11.7 < hemoglobin <= 13.8:
            print("\n\t Hemoglobin : Normal")
 if flag == 1:
    print("\n\t Hemoglobin : LOW ")
    # # num = int(input("Press 1 to get some remedies to " "maintain  : "))
    # if num == 1:
    print("\n\t ")
    print("\nIntake: \n1.Iron-rich food\n2.Vitamin\n3.Folic acid\n4.Betroot\n5.pomegranate")
 if flag1 == 1:
    num = int(input("According to your Hemoglobin analysis,You have a HIGH Hemoglobin,Press 1 to get some remedies to "
                    "maintain   : "))
    if num == 1:
        print("\n1.Avoid using performance-enhancing drugs.\n2.Eat a nutritious diet with plenty of fruits and "
              "vegetables.\n3.Stay hydrated by drinking plenty of water and other liquids.\n4.Quit smoking.")

# import module
import fontstyle

# format text
text = fontstyle.apply('GEEKSFORGEEKS', 'bold/Italic/red/GREEN_BG')

# display text
print(text)

